apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: nginx
  selector:
    app: explorer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  selector:
    matchLabels:
      app: explorer
  replicas: 1
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
        - name: explorer
          image: planetariumhq/cosmwasm-explorer:latest
          ports:
            - containerPort: 80
              name: nginx
