version: "3"
services:
  node:
    build:
      context: .
      args:
        - arch=${ARCH:-aarch64}
    command: ./setup_and_run.sh
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
    environment:
      - UNSAFE_CORS=1
      - ADAM=1
      - MONIKER=adam
      - PROMETHEUS=1
      - MNEMONIC=video time blush urge gate veteran wood gate witness cube gown humor funny olympic spider muffin label bounce inquiry payment inmate collect save uniform
    volumes:
      - ~/:/root